version: '3'

services:
  web:
    image: s0ultak3r/dockerflask:$RELEVANT_DOCKER_TAG
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_HOST=db
      - MYSQL_DATABASE=flask_db
    restart: always
  db:
    image: s0ultak3r/dockerdb:$RELEVANT_DOCKER_TAG
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheusconfig.yml:/etc/prometheus/prometheus.yml
    command: ["--web.enable-admin-api", "--web.enable-lifecycle", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.retention.time=6h"]
    environment:
      - prometheus_multiproc_dir=/tmp
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus



volumes:
  db_data:
  grafana_data:

