version: '3'

services:
  web:
    build: ./flask-app
    image: s0ultak3r/dockerflask
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_HOST=db
      - MYSQL_DATABASE=flask_db
    restart: always
  db:
    build: ./mysql
    image: s0ultak3r/dockerdb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: ["--web.enable-admin-api", "--web.enable-lifecycle", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.retention.time=6h"]
    environment:
      - prometheus_multiproc_dir=/tmp


volumes:
  db_data:
