- name: Install Apache HTTP Server, GIT, SSH, Flask, and Run Flask project
  hosts: all
  become: true

  tasks:
    - name: Update package cache
      package:
        name: '*'
        state: latest

    - name: Install packages
      package:
        name:
          - httpd
          - git
          - openssh-server
          - python3-pip
        state: present

    - name: Stop Apache service
      service:
        name: httpd
        state: stopped
        enabled: true
      when: "'aws_hostsHTTPD' in group_names"

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: true
      when: "'aws_hostsHTTPD' in group_names"

    - name: Install Flask
      pip:
        name: flask
        state: present
      when: "'aws_hostsFlask' in group_names"

    - name: Install project requirements
      pip:
        requirements: /flask/PythonFlask/docker-curriculum/flask-app/requirements.txt
      when: "'aws_hostsFlask' in group_names"

    - name: Run Flask project
      command: nohup python3 /flask/PythonFlask/docker-curriculum/flask-app/app.py --port={{ flask_port }}
      async: 0
      poll: 0
      when: "'aws_hostsFlask' in group_names"
